### ISSUE TITLE
Export snippet parser issue has been resolved on Org side

### ISSUE THREAD

**Issue by yantar92** [lucasvreis/org-parser#1]
https://github.com/lucasvreis/org-parser/blob/master/SPEC.org#export-snippets

The described problem should be resolved in https://git.savannah.gnu.org/cgit/emacs/org-mode.git/commit/?id=96529e933b445dce52e4e904695f1d538c3e0e7f

The provided example is not an @html export snippet because snippet is an object and cannot span over multiple paragraph elements.

**Comment by lucasvreis** [comment]
Thanks! Teco told me about the patch last week. The SPEC.org file is a very informal thing that I wrote because he asked me, and I will probably delete it or move it elsewhere later. For now I have updated the file accordingly.
